//import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { ReactNode } from "react";
import Navbar from "@/components/nav-bar";
import { auth } from "@/lib/auth";

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

type LayoutProps = {
  children: ReactNode;
};
export default async function RootLayout({ children }: LayoutProps) {
  const session = await auth()

  return (
    <html>
      <body>
        {session && <Navbar />}
        <main className="flex items-center justify-center min-h-screen bg-gray-100">
          <div className="bg-white p-8 rounded-lg shadow-md w-full max-w-md">
            {children}
          </div>
        </main>
      </body>
      </html>
   
  )
};

//export { metadata };
//export default Layout;
