import type { Product, CategoryOption } from "./types"

export const categoryOptions: CategoryOption[] = [
  {
    id: "skincare",
    label: "Skincare",
    icon: "droplet",
    subcategories: [
      { id: "cleansers", label: "Cleansers" },
      { id: "toners", label: "Toners & Mists" },
      { id: "serums", label: "Serums & Ampoules" },
      { id: "moisturizers", label: "Moisturizers & Creams" },
      { id: "eyecare", label: "Eye Care" },
      { id: "masks", label: "Masks & Treatments" },
      { id: "sunscreen", label: "Sunscreen & UV Protection" },
    ],
  },
  {
    id: "makeup",
    label: "Makeup",
    icon: "palette",
    subcategories: [
      { id: "face", label: "Face Makeup" },
      { id: "lip", label: "Lip Products" },
      { id: "eye", label: "Eye Makeup" },
      { id: "base", label: "Makeup Base & Primers" },
      { id: "setting", label: "Setting & Finishing Products" },
    ],
  },
  {
    id: "hairbody",
    label: "Hair & Body",
    icon: "shower-head",
    subcategories: [
      { id: "shampoo", label: "Shampoo & Conditioners" },
      { id: "treatments", label: "Hair Treatments & Oils" },
      { id: "bodywash", label: "Body Wash & Soaps" },
      { id: "lotions", label: "Body Lotions & Creams" },
      { id: "hand", label: "Hand & Foot Care" },
      { id: "scrubs", label: "Body Scrubs & Exfoliators" },
      { id: "perfumes", label: "Deodorants & Perfumes" },
    ],
  },
]

// Sample mock data - in a real application, this would come from an API
export const mockProducts: Product[] = [
  // SKINCARE - CLEANSERS
  {
    id: "sc1",
    name: "Green Tea Foam Cleanser",
    description: "Gentle foam cleanser with green tea extract for daily cleansing",
    price: 12.0,
    volume: "150ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "cleansers",
    rank: 1,
    rating: 4.6,
    reviewCount: 856,
    likes: 2100,
    trending: false,
    date: "2023-08-15",
    tags: ["sensitive", "dry", "combination"],
  },
  {
    id: "sc2",
    name: "Jeju Volcanic Pore Cleansing Foam",
    description: "Deep cleansing foam with volcanic clusters to remove impurities",
    price: 15.0,
    volume: "150ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "cleansers",
    rank: 2,
    rating: 4.7,
    reviewCount: 987,
    likes: 2890,
    trending: true,
    date: "2023-09-20",
    tags: ["oily", "combination"],
  },
  {
    id: "sc3",
    name: "Bija Trouble Facial Foam",
    description: "Purifying facial foam with bija seed oil for troubled skin",
    price: 13.0,
    volume: "150ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "cleansers",
    rank: 3,
    rating: 4.5,
    reviewCount: 723,
    likes: 1850,
    trending: false,
    date: "2023-07-10",
    tags: ["oily", "sensitive", "combination"],
  },

  // SKINCARE - TONERS & MISTS
  {
    id: "st1",
    name: "Green Tea Balancing Skin",
    description: "Balancing toner with green tea extract for combination skin",
    price: 20.0,
    volume: "200ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "toners",
    rank: 1,
    rating: 4.7,
    reviewCount: 876,
    likes: 2134,
    trending: false,
    date: "2023-06-15",
    tags: ["combination", "sensitive"],
  },
  {
    id: "st2",
    name: "Brightening Pore Skin",
    description: "Brightening toner that minimizes pores and evens skin tone",
    price: 22.0,
    volume: "200ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "toners",
    rank: 2,
    rating: 4.6,
    reviewCount: 754,
    likes: 1932,
    trending: false,
    date: "2023-05-20",
    tags: ["combination", "dry"],
  },
  {
    id: "st3",
    name: "Volcanic Pore Toner",
    description: "Pore-refining toner with volcanic ash to control sebum",
    price: 18.0,
    volume: "200ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "toners",
    rank: 3,
    rating: 4.5,
    reviewCount: 687,
    likes: 1765,
    trending: false,
    date: "2023-04-25",
    tags: ["oily", "combination"],
  },

  // SKINCARE - SERUMS & AMPOULES
  {
    id: "ss1",
    name: "Green Tea Seed Serum",
    description: "Hydrating serum with Jeju green tea extract for intense moisture",
    price: 27.0,
    volume: "80ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "serums",
    rank: 1,
    rating: 4.8,
    reviewCount: 1243,
    likes: 3567,
    trending: true,
    date: "2023-10-15",
    tags: ["sensitive", "dry"],
  },
  {
    id: "ss2",
    name: "Retinol Cica Repair Ampoule",
    description: "Anti-aging ampoule with retinol and cica for skin repair",
    price: 32.0,
    volume: "30ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "serums",
    rank: 2,
    rating: 4.7,
    reviewCount: 965,
    likes: 2876,
    trending: false,
    date: "2023-09-05",
    tags: ["dry", "sensitive"],
  },
  {
    id: "ss3",
    name: "Black Tea Youth Enhancing Ampoule",
    description: "Anti-aging ampoule with black tea extract for firmer skin",
    price: 35.0,
    volume: "30ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "serums",
    rank: 3,
    rating: 4.6,
    reviewCount: 832,
    likes: 2543,
    trending: false,
    date: "2023-08-10",
    tags: ["dry", "combination"],
  },

  // SKINCARE - MOISTURIZERS & CREAMS
  {
    id: "sm1",
    name: "Green Tea Seed Cream",
    description: "Hydrating cream with green tea seed oil for deep moisture",
    price: 25.0,
    volume: "50ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "moisturizers",
    rank: 1,
    rating: 4.7,
    reviewCount: 943,
    likes: 2765,
    trending: false,
    date: "2023-07-15",
    tags: ["dry", "sensitive"],
  },
  {
    id: "sm2",
    name: "Bija Cica Balm",
    description: "Soothing balm with cica and bija seed oil for troubled skin",
    price: 24.0,
    volume: "40ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "moisturizers",
    rank: 2,
    rating: 4.8,
    reviewCount: 876,
    likes: 2543,
    trending: false,
    date: "2023-06-20",
    tags: ["sensitive", "combination"],
  },
  {
    id: "sm3",
    name: "Cherry Blossom Jelly Cream",
    description: "Lightweight jelly cream with cherry blossom extract for brightening",
    price: 22.0,
    volume: "50ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "moisturizers",
    rank: 3,
    rating: 4.6,
    reviewCount: 765,
    likes: 2321,
    trending: false,
    date: "2023-05-25",
    tags: ["combination", "oily"],
  },

  // SKINCARE - EYE CARE
  {
    id: "se1",
    name: "Black Tea Youth Enhancing Eye Serum",
    description: "Anti-aging eye serum with black tea extract for firmer eye area",
    price: 30.0,
    volume: "15ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "eyecare",
    rank: 1,
    rating: 4.7,
    reviewCount: 654,
    likes: 1987,
    trending: false,
    date: "2023-04-15",
    tags: ["dry", "sensitive"],
  },
  {
    id: "se2",
    name: "Jeju Orchid Eye Cream",
    description: "Nourishing eye cream with orchid extract for brightening",
    price: 28.0,
    volume: "30ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "eyecare",
    rank: 2,
    rating: 4.6,
    reviewCount: 587,
    likes: 1765,
    trending: false,
    date: "2023-03-20",
    tags: ["dry", "combination"],
  },
  {
    id: "se3",
    name: "Green Tea Seed Eye & Face Ball",
    description: "Cooling eye and face massager with green tea seed oil",
    price: 25.0,
    volume: "10ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "eyecare",
    rank: 3,
    rating: 4.5,
    reviewCount: 498,
    likes: 1543,
    trending: false,
    date: "2023-02-25",
    tags: ["sensitive", "combination"],
  },

  // SKINCARE - MASKS & TREATMENTS
  {
    id: "sma1",
    name: "Super Volcanic Pore Clay Mask",
    description: "Intensive pore care mask with volcanic ash to remove sebum",
    price: 16.0,
    volume: "100ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "masks",
    rank: 1,
    rating: 4.8,
    reviewCount: 1098,
    likes: 2567,
    trending: false,
    date: "2023-05-22",
    tags: ["oily", "combination"],
  },
  {
    id: "sma2",
    name: "Brightening Pore Sleeping Mask",
    description: "Overnight mask that brightens skin and minimizes pores",
    price: 18.0,
    volume: "100ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "masks",
    rank: 2,
    rating: 4.7,
    reviewCount: 876,
    likes: 2345,
    trending: false,
    date: "2023-04-18",
    tags: ["combination", "dry"],
  },
  {
    id: "sma3",
    name: "Bija Trouble Spot Essence",
    description: "Targeted treatment for blemishes with bija seed oil",
    price: 15.0,
    volume: "15ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "masks",
    rank: 3,
    rating: 4.6,
    reviewCount: 765,
    likes: 2123,
    trending: false,
    date: "2023-03-15",
    tags: ["oily", "sensitive"],
  },

  // SKINCARE - SUNSCREEN & UV PROTECTION
  {
    id: "su1",
    name: "Tone Up No Sebum Sunscreen",
    description: "Brightening sunscreen with sebum control for oily skin",
    price: 14.5,
    volume: "50ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "sunscreen",
    rank: 1,
    rating: 4.7,
    reviewCount: 789,
    likes: 1876,
    trending: true,
    date: "2023-03-25",
    tags: ["oily", "combination"],
  },
  {
    id: "su2",
    name: "Intensive Long-Lasting Sunscreen",
    description: "Water-resistant sunscreen with SPF50+ for outdoor activities",
    price: 16.0,
    volume: "50ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "sunscreen",
    rank: 2,
    rating: 4.6,
    reviewCount: 687,
    likes: 1765,
    trending: false,
    date: "2023-02-20",
    tags: ["dry", "combination"],
  },
  {
    id: "su3",
    name: "Truecare Non-Nano Sunscreen",
    description: "Gentle sunscreen with non-nano particles for sensitive skin",
    price: 18.0,
    volume: "60ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "skincare",
    subcategory: "sunscreen",
    rank: 3,
    rating: 4.5,
    reviewCount: 576,
    likes: 1654,
    trending: false,
    date: "2023-01-25",
    tags: ["sensitive", "dry"],
  },

  // MAKEUP - FACE MAKEUP
  {
    id: "mf1",
    name: "No Sebum Mineral Powder",
    description: "Oil control powder with Jeju minerals for a matte finish",
    price: 8.5,
    volume: "5g",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "makeup",
    subcategory: "face",
    rank: 1,
    rating: 4.9,
    reviewCount: 2156,
    likes: 4102,
    trending: true,
    date: "2023-11-05",
    tags: ["oily", "vegan"],
  },
  {
    id: "mf2",
    name: "Smart Drawing Foundation",
    description: "Easy-to-apply liquid foundation with buildable coverage",
    price: 20.0,
    volume: "30ml",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "makeup",
    subcategory: "face",
    rank: 2,
    rating: 4.7,
    reviewCount: 987,
    likes: 2765,
    trending: false,
    date: "2023-10-10",
    tags: ["dry", "combination"],
  },
  {
    id: "mf3",
    name: "Mineral Cover Fit Cushion",
    description: "Cushion foundation with mineral ingredients for natural coverage",
    price: 25.0,
    volume: "15g",
    image: "/placeholder.svg?height=200&width=300",
    brand: "Innisfree",
    category: "makeup",
    subcategory: "face",
    rank: 3,
    rating: 4.6,
    reviewCount: 876,
    likes: 2543,
    trending: false,
    date: "2023-09-15",
    tags: ["combination", "sensitive"],
  },

  // Add more products for other subcategories as needed...
  // This is a simplified version of the mock data
  // In a real application, this would be fetched from an API
]

